### ISSUE TITLE
Suggestion: don't print map name on levels with NoAutosaveHint

### ISSUE THREAD

**Issue by mmaulwurff** [jekyllgrim/MapNamePrint#1]
[v1.5 Doom 64: Retribution](https://www.doomworld.com/forum/topic/91854-v15-doom-64-retribution/):

![image](https://github.com/jekyllgrim/MapNamePrint/assets/742823/6715f711-81c3-439c-8336-4146f1c62928)

```
map MAP00 lookup "D64HUSTR_0" // The Story so Far
{
	levelnum = 0
	next = "MAP01"
	secretnext = "MAP01"
	sky1 = "ISUCK"
	cluster = 1
	par = 0
	music = "D_SILENT" // Changes automatically to $MUS_INTRO if unskipped!
	nointermission
	noautosavehint
}
```

----

From ZDoom [wiki](https://zdoom.org/wiki/MAPINFO/Map_definition) about NoAutosaveHint:
> Use this for "fake" levels that are used only for scripted sequences.

There is a slim chance that someone uses this for a regular level for some reason, however.

----

This can be probably checked with `Level.info.flags2` and `LEVEL2_NOAUTOSAVEHINT` flag.

**Comment by jekyllgrim** [comment]
Thanks for the idea. Added in ee7ad966a0b462b9f67b33ce0770f67ba60a25f4.
